name: GitHub Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [17, 19]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        cache: 'maven'

    - name: Build with Maven (Linux)
      run: xvfb-run -a mvn -B package --file pom.xml

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PixelitorJAR-${{ steps.date.outputs.date }}
        path: |
          target/*.jar
          !target/original-*.jar
