name: GitHub Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17, 20 ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        cache: 'maven'

    - name: Build with Maven (Linux)
      run: xvfb-run -a mvn -B package --file pom.xml

    - name: Put the current date in the environment file
      run: |
        echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
       
    - name: Archive artifacts
      if: matrix.java-version == 17
      uses: actions/upload-artifact@v3
      with:
        name: PixelitorJAR-${{ env.DATE }}
        path: |
          target/*.jar
          !target/original-*.jar
