name: GitHub Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build with Maven
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn -B package --file pom.xml

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PixelitorJAR-${{ steps.date.outputs.date }}
        path: |
          target/*.jar
          !target/original-*.jar
